//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeLi.FormChart.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KeLi.FormChart.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ArrayOfResourceDetail xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///    &lt;ResourceDetail&gt;
        ///        &lt;CategoryName&gt;BF1&lt;/CategoryName&gt;
        ///        &lt;UsedNum&gt;180&lt;/UsedNum&gt;
        ///        &lt;UsableNum&gt;10&lt;/UsableNum&gt;
        ///        &lt;ReservationNum&gt;10&lt;/ReservationNum&gt;
        ///    &lt;/ResourceDetail&gt;
        ///    &lt;ResourceDetail&gt;
        ///        &lt;CategoryName&gt;BF2&lt;/CategoryName&gt;
        ///        &lt;UsedNum&gt;180&lt;/UsedNum&gt;
        ///        &lt;UsableNum&gt;10&lt;/UsableNum&gt;
        ///        &lt;Reservat [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResourceDetailData {
            get {
                return ResourceManager.GetString("ResourceDetailData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;
        ///&lt;ArrayOfResourceTotal xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///    &lt;ResourceTotal&gt;
        ///        &lt;CategoryName&gt;Usable Count&lt;/CategoryName&gt;
        ///        &lt;CategoryNum&gt;2335&lt;/CategoryNum&gt;
        ///    &lt;/ResourceTotal&gt;
        ///    &lt;ResourceTotal&gt;
        ///        &lt;CategoryName&gt;Reserved Count&lt;/CategoryName&gt;
        ///        &lt;CategoryNum&gt;1192&lt;/CategoryNum&gt;
        ///    &lt;/ResourceTotal&gt;
        ///    &lt;ResourceTotal&gt;
        ///        &lt;CategoryName&gt;Total Count&lt;/CategoryName&gt;
        ///      [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResourceTotalData {
            get {
                return ResourceManager.GetString("ResourceTotalData", resourceCulture);
            }
        }
    }
}
